#!/bin/sh

echo -e "********** Stash files"
git add -A
git stash -q

echo -e "********** Validate with tests"
npx turbo run test --force
statusTest=$?

echo -e "********** Stash pop files"
git stash pop -q
git reset -q HEAD

RED='\033[0;31m' # Red
NC='\033[0m' # No Color

if [[ $statusTest -eq 1 ]] || [[ $statusRemote -eq 1 ]]
then
  echo -e "********** Error log"
fi

if [[ $statusTest -eq 1 ]]
then
    echo -e "${RED}Test failed${NC}"
fi

if [[ $statusRemote -eq 1 ]]
then
    echo -e "${RED}Dependency validation failed${NC}"
fi

if [[ $statusTest -eq 1 ]] || [[ $statusRemote -eq 1 ]]
then
  exit 1
else
  exit 0
fi